<?php

/**
 * Implements hook_theme().
 */
function competition_winners_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__competition_winner_container' => [
      'variables' => ['winners' => []],
      'template' => 'paragraph--competition-winner-container',
      'path' => \Drupal::service('extension.list.module')->getPath('competition_winners') . '/templates',    ],
  ];
}

/**
 * Implements preprocess_paragraph().
 *  
 * Prepares variables for the Competition Winners paragraph type.
 */
function competition_winners_preprocess_paragraph__competition_winner_container(array &$variables) {
  $paragraph = $variables['elements']['#paragraph'];

  if ($paragraph->hasField('field_winners_list') && !$paragraph->field_winners_list->isEmpty()) {
    foreach ($paragraph->get('field_winners_list') as $item) {
      if ($winner = $item->entity) {
        $variables['winners'][] = $winner;
      }
    }
  }
}